repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: .githooks/pre-commit
        name: .githooks/pre-commit
        entry: .githooks/pre-commit
        language: system
        always_run: true
      - id: update-documentation
        name: update-documentation
        description: This hook ensures that json-schema documentation is always up to date
        language: python
        additional_dependencies: [cidc_schemas,jinja2,jsonschema]
        entry: python ./docs/generate_docs.py