repos:
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: .githooks/pre-commit
        name: .githooks/pre-commit
        entry: .githooks/pre-commit
        language: system
