language: python
install:
  - pip install -r requirements.dev.txt
script:
  - pytest
  - black --check cidc_schemas tests docs --target-version=py36
deploy:
  provider: pypi
  # TODO: should this be on a shared CIDC account?
  username: jlurye-ksg
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    branch: master