language: python
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: pypi
  # TODO: should this be on a shared CIDC account?
  username: jlurye-ksg
  password: $PYPI_PASSWORD
  on:
    branch: master